# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Baltimore Tax Sale
tagline:          'Data and Analysis'
description:      'Analysis of data from the annual Baltimore tax sale. Made by <a href="https://twitter.com/Ryan_J_Smith" target="_blank">@Ryan_J_Smith</a>.'
url:              http://Ryan-J-Smith.github.io/baltimore-tax-sale
baseurl:          ""

author:
  name:           'Ryan J. Smith'
  url:            https://twitter.com/Ryan_J_Smith

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Ryan-J-Smith/baltimore-tax-sale
